# Site settings
name: MeditLon
title: MeditLon | Personal Page For Public
description: I'm MeditLon, a design-minded one who is Still learning New Stuff, FOSS Supporter & Cyber Nerd
url: https://meditlon.github.io/
baseurl: ''
email: hi@mdtln.slmail.me
cover: https://meditlon.github.io/img/og.png
logo: https://meditlon.github.io/img/emojis/technologist.png
resume: https://meditlon.github.io/resume.pdf
social:
  - title: email
    url: mailto:hi@mdtln.slmail.me
  - title: twitter
    url: https://twitter.com/meditlon
  - title: instagram
    url: https://instagram.com/meditlon
  - title: github
    url: https://github.com/meditlon

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
